### ISSUE TITLE
请问是否支持辅助通道？

### ISSUE THREAD

**Issue by jaggerwang** [OpenFlutter/rammus#1]
在小米手机上调试，应用在前台可以收到推送消息，放到后台就不行。看 [官方文档](https://help.aliyun.com/document_detail/30067.html?spm=a2c4g.11186623.6.626.69f252e70IT3HG) 说需要配置辅助通道，但查看本项目的 `build.gradle` 里面并没有导入相关 java 包。

是不是表示不支持？还是说只需要在自己的应用里导入相关 java 包，配置各个厂商的应用信息即可？

**Comment by jaggerwang** [comment]
另外在 VSCode 里面提示无法找到 `com.jarvanmo.rammus.RammusPushIntentService` 这个 java 包，虽然可以编译通过。

<img width="1280" alt="屏幕快照 2019-09-14 16 27 32" src="https://user-images.githubusercontent.com/1255011/64905566-c4a15e80-d70c-11e9-8974-20895fe7cfe7.png">

**Comment by jaggerwang** [comment]
另外在 VSCode 里面提示无法找到 `com.jarvanmo.rammus.RammusPushIntentService` 这个 java 包，虽然可以编译通过。

<img width="1280" alt="屏幕快照 2019-09-14 16 27 32" src="https://user-images.githubusercontent.com/1255011/64905566-c4a15e80-d70c-11e9-8974-20895fe7cfe7.png">

**Comment by JarvanMo** [comment]
1想支持厂商通道可以fork本项目然后进行PR。
2看不到出来什么找到找不到的。vscode又不是android studio。

**Comment by jaggerwang** [comment]
Shit！提了等于没提，受不了某些国人开源项目的那样儿。直接回答不支持不就得了嘛。那么明显的红色下划线提示，再说这个需要看出吗，不知道就说不知道好了。

**Comment by JarvanMo** [comment]
@jaggerwang 嘴干净点。我们开源作者又不欠你的！！！好心开源出来，你在骂骂咧咧地，你资助过一分钱吗？瞅你们这些用户能给带开源社区带来什么作用？作出一分贡献了？为开源项目PR过代码吗？写过一个开源项目吗？除了一味索求还会骂人是吧？我们欠你的？你睁大你的牛眼看看是哪个单词划红线了？知道不知道有种红线叫spell check?你特么的一个flutter项目在问android的导包有没有问题，你是脑子锈透了？你不特么的去android studio看跑这骂人？别在这秀你的无知。

**Comment by JarvanMo** [comment]
@jaggerwang 自己屁贡献没做出来跑这指责别人？我是不是还要这教你怎么写android?你特么的受不了就你自己写去，别没事在这瞎吠。

**Comment by JarvanMo** [comment]
@jaggerwang 我们开源作者的时间就不是时间？只有你的时间是时间？只你自己需要工作，动点脑子。

**Comment by JarvanMo** [comment]
对，我怕你不懂，告诉你spell cehck的中文意思叫拼写检查。

**Comment by JarvanMo** [comment]
@jaggerwang 和我解释一下什么叫spell check？什么是导包错误？ 我是不是还要从重头教你flutter? 教你iOS？教android?  遇到问题自己先动动脑子。
![image](https://user-images.githubusercontent.com/11608487/64907345-a1ce7480-d723-11e9-95ac-5e1670a6063b.png)
就这般没脑子？

**Comment by JarvanMo** [comment]
记住，中国的开源社区就让像你这样的人毁了。

**Comment by JarvanMo** [comment]
还有你的理解能力在下实在是佩服。

`1想支持厂商通道可以fork本项目然后进行PR。`


如果有厂商通道，还用fork?

**Comment by jaggerwang** [comment]
不要以为只有编写代码才是为开源项目做贡献，提交 Issue 同样也是，我有没有开源项目你可以自己去看一下。别人来提问是想得到解答，而不是你随便怼一句自己去实现。如果不支持直接说就行了，没人逼你。就说了一句 SHIT，看把你急得跟猴儿一样上蹿下跳，还把别人的个人资料贴出来。你是过得有多压抑，不觉得自己的行为很恶劣吗？每个人都有自己擅长和不擅长的，即便我想学 Android，也不至于找你这种水准的。

关于第二个问题到底是拼写错误还是包找不到，就不要不懂装懂的来教育别人了，这让人觉得很可笑！

<img width="669" alt="屏幕快照 2019-09-15 16 47 29" src="https://user-images.githubusercontent.com/1255011/64919208-a6099900-d7da-11e9-9bb0-da9d922c054b.png">

![屏幕快照 2019-09-15 17 03 56](https://user-images.githubusercontent.com/1255011/64919254-e832da80-d7da-11e9-8fe2-cc77c80e1074.png)
![屏幕快照 2019-09-15 17 04 27](https://user-images.githubusercontent.com/1255011/64919259-ec5ef800-d7da-11e9-8156-81dd80dda513.png)

**Comment by JarvanMo** [comment]
长点脑子可以吗？还就一句shit。你没侮辱国内开源作者？还就是找不到，你知道vscode是什么不？你知道Android studio是什么不？找不到拿空气编译？你这相当于Android studio打开flutter项目，然后打开Java文件问为什么报红。长点脑子。

**Comment by JarvanMo** [comment]
没有的功能让你自己PR有问题？我们欠你的？

**Comment by JarvanMo** [comment]
自己想一想，代码不进行index 能系统能找得到？index的基础是什么？想过吗？你以为这是js?

**Comment by JarvanMo** [comment]
真是牛B坏了，骂人是不是骂习惯了？shit都不是脏话了？

**Comment by JarvanMo** [comment]
这么大的人了，你自己想想你的所作所为，到底是不是合适？你要是觉得shit合适，那请你对自己的家人每天说几遍shit。我们辛辛苦苦写这些，是让你们来骂的？你是我的付费用户还是怎么的？现在你们白嫖的都这么理直气壮？
