### ISSUE TITLE
厂商通道怎么使用呢

### ISSUE THREAD

**Issue by Zrincet** [OpenFlutter/rammus#10]
阿里推送里面的厂商通道

**Comment by JarvanMo** [comment]
not supported now------------------ 原始邮件 ------------------
发件人: "Princet"<notifications@github.com>
发送时间: 2020年4月6日(星期一) 中午12:14
收件人: "OpenFlutter/rammus"<rammus@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: [OpenFlutter/rammus] 厂商通道怎么使用呢 (#10)




 
阿里推送里面的厂商通道
 
&mdash;

**Comment by JarvanMo** [comment]
想用厂商通道可以PR。
