### ISSUE TITLE
本插件和tobias插件ios上有冲突

### ISSUE THREAD

**Issue by jinxing88** [OpenFlutter/rammus#23]
tobias: ^1.6.0+1
rammus: ^1.2.1

 duplicate symbol '_OBJC_METACLASS_$_UTDIDKeychainItemWrapper' in:
        /Users/Shared/workspace/flutter/flutter_cpp/ios/Pods/AlipaySDK-iOS/AlipaySDK.framework/AlipaySDK
        /Users/Shared/workspace/flutter/flutter_cpp/ios/Pods/AlicloudUTDID/utdid/UTDID.framework/UTDID(UTDIDKeychainItemWrapper.o)
    duplicate symbol '_OBJC_IVAR_$_UTDIDKeychainItemWrapper.keychainItemData' in:
        /Users/Shared/workspace/flutter/flutter_cpp/ios/Pods/AlipaySDK-iOS/AlipaySDK.framework/AlipaySDK
        /Users/Shared/workspace/flutter/flutter_cpp/ios/Pods/AlicloudUTDID/utdid/UTDID.framework/UTDID(UTDIDKeychainItemWrapper.o)
    duplicate symbol '_OBJC_CLASS_$_UTDIDPersistentConf' in:
        /Users/Shared/workspace/flutter/flutter_cpp/ios/Pods/AlipaySDK-iOS/AlipaySDK.framework/AlipaySDK
        /Users/Shared/workspace/flutter/flutter_cpp/ios/Pods/AlicloudUTDID/utdid/UTDID.framework/UTDID(UTDIDPersistentConf.o)
    duplicate symbol '_OBJC_METACLASS_$_UTDIDPersistentConf' in:
        /Users/Shared/workspace/flutter/flutter_cpp/ios/Pods/AlipaySDK-iOS/AlipaySDK.framework/AlipaySDK
        /Users/Shared/workspace/flutter/flutter_cpp/ios/Pods/AlicloudUTDID/utdid/UTDID.framework/UTDID(UTDIDPersistentConf.o)
    duplicate symbol '_OBJC_CLASS_$_UTDIDPersistentFile' in:
        /Users/Shared/workspace/flutter/flutter_cpp/ios/Pods/AlipaySDK-iOS/AlipaySDK.framework/AlipaySDK
        /Users/Shared/workspace/flutter/flutter_cpp/ios/Pods/AlicloudUTDID/utdid/UTDID.framework/UTDID(UTDIDPersistentFile.o)
    duplicate symbol '_OBJC_METACLASS_$_UTDIDPersistentFile' in:
        /Users/Shared/workspace/flutter/flutter_cpp/ios/Pods/AlipaySDK-iOS/AlipaySDK.framework/AlipaySDK
        /Users/Shared/workspace/flutter/flutter_cpp/ios/Pods/AlicloudUTDID/utdid/UTDID.framework/UTDID(UTDIDPersistentFile.o)
    ld: 32 duplicate symbols for architecture arm64
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
    note: Using new build system
    note: Planning build
    note: Constructing build description

Could not build the precompiled application for the device.

**Comment by JarvanMo** [comment]
Uuid重复了，可以自己换个no uuid版本------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;叶尼水&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年7月28日(星期二) 下午5:01
收件人:&nbsp;&quot;OpenFlutter/rammus&quot;<rammus@noreply.github.com&gt;;
抄送:&nbsp;&quot;Subscribed&quot;<subscribed@noreply.github.com&gt;;
主题:&nbsp;[OpenFlutter/rammus] 本插件和tobias插件ios上有冲突 (#23)

**Comment by jinxing88** [comment]
> Uuid重复了，可以自己换个no uuid版本------------------&nbsp;原始邮件&nbsp;------------------ 发件人:&nbsp;&quot;叶尼水&quot;<notifications@github.com&gt; 发送时间:&nbsp;2020年7月28日(星期二) 下午5:01 收件人:&nbsp;&quot;OpenFlutter/rammus&quot;<rammus@noreply.github.com&gt;; 抄送:&nbsp;&quot;Subscribed&quot;<subscribed@noreply.github.com&gt;; 主题:&nbsp;[OpenFlutter/rammus] 本插件和tobias插件ios上有冲突 (#23)

非常感谢，搞定了

**Comment by gaoshanyu** [comment]
我们也遇到这个问题，请教一下怎么换？有示例吗？

**Comment by gaoshanyu** [comment]
我参考了这个链接：
https://github.com/flutter/flutter/issues/17978
导入成功了。
AlicloudUtils.framework, CloudPushSDK.framework, UTMini.framework 放入了 `rammus/ios/`，修改了 `rammus/ios/rammus.podspec` 如下：
```
Pod::Spec.new do |s|
  s.name             = 'rammus'
  s.version          = '0.0.1'
  s.summary          = 'A new Flutter plugin for AliCloud push.'
  s.description      = <<-DESC
A new Flutter plugin for AliCloud push.
                       DESC
  s.homepage         = 'http://example.com'
  s.license          = { :file => '../LICENSE' }
  s.author           = { 'Your Company' => 'email@example.com' }
  s.source           = { :path => '.' }
  s.source_files = 'Classes/**/*'
  s.public_header_files = 'Classes/**/*.h'
  s.dependency 'Flutter'

  s.preserve_paths = 'AlicloudUtils.framework', 'CloudPushSDK.framework', 'UTMini.framework'
  s.xcconfig = { 'OTHER_LDFLAGS' => '-framework AlicloudUtils, -framework CloudPushSDK, -framework UTMini' }
  s.vendored_frameworks = 'AlicloudUtils.framework', 'CloudPushSDK.framework', 'UTMini.framework'

  s.frameworks = ["SystemConfiguration", "CoreTelephony"]
  s.libraries = ["z", "sqlite3.0", "resolv"]
  s.static_framework = true

  s.ios.deployment_target = '10.0'
end
```


暂时是把冲突解决了，还未测试推送功能是否有影响，稍后更新。

**Comment by gaoshanyu** [comment]
上面这个方法很好用，iOS 没问题了。

但是现在 Android 也出现了：

`Duplicate class com.ta.utdid2.a.a.a found in modules jetified-alicloud-android-utdid-2.5.1-proguard (com.aliyun.ams:alicloud-android-utdid:2.5.1-proguard) and jetified-alipaysdk-15.8.03.210428205839-runtime (:alipaysdk-15.8.03.210428205839:)`

我对 Android 配置不熟，正在找寻解决方法。

**Comment by JarvanMo** [comment]
先把Tobias降低一个小小版本------------------&nbsp;原始邮件&nbsp;------------------
***@***.***&gt;
发送时间:&nbsp;2021年6月28日(星期一) 中午12:05
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [OpenFlutter/rammus] 本插件和tobias插件ios上有冲突 (#23)

**Comment by gaoshanyu** [comment]
@JarvanMo 非常感谢，tobias: 2.1.1 有冲突报错，降到 tobias: 2.1.0 就好了！
