### ISSUE TITLE
pushService 10109/网络连接失败,请检查网络配置

### ISSUE THREAD

**Issue by huijimuhe** [OpenFlutter/rammus#4]
你好，我遇到10109错误码

按文档仔细检查了配置，小米mix2s真机测试，未发现问题所在，想请教一下应该注意什么地方呢？

**Comment by JarvanMo** [comment]
我也不知道。我不用阿里云推送。更多信息请去阿里云推送官网查询。

**Comment by huijimuhe** [comment]
额，这个项目就是阿里云的啊，汗。
阿里云的文档也看了，找不出头绪

**Comment by JarvanMo** [comment]
是阿里云的也不意思味着什么 。不意味着我懂阿里云推送啊，我在文档里说的很清楚，这个项目是别人付费开发，然后开源。我做的工作只不过是桥接，然后调通并开源。做一个插件并不需要精通SDK。

**Comment by huijimuhe** [comment]
不好意思打扰了
