### ISSUE TITLE
监听到了消息却未在通知栏生成通知,需要配合其他发送通知的插件使用吗?

### ISSUE THREAD

**Issue by jiangyw111** [OpenFlutter/rammus#41]
rammus.onNotification.listen收到了消息,却未在通知栏生成消息通知,需配合类似flutter_local_notifications等插件另发送通知吗?

**Comment by ZRXXUAN** [comment]
您好，这个问题解决了么？

**Comment by ZRXXUAN** [comment]
> 您好，这个问题解决了么？

**Comment by jhfkf** [comment]
麻烦问下，你是怎么解决的？
