### ISSUE TITLE
监听无效呢？咋回事，有人遇到过吗？

### ISSUE THREAD

**Issue by FreAirLy** [OpenFlutter/rammus#5]
目前在原生能收到通知，但是在flutter里面添加的监听无效，有人遇到过这个情况吗

**Comment by FreAirLy** [comment]
FlutterMethodChannel *_methodChannel;
弱引用问题，改一下就可以，希望楼主check一下

**Comment by JarvanMo** [comment]
@FreAirLy 麻烦提下PR以修复此问题。

**Comment by jkLennon** [comment]
@FreAirLy 楼主监听无效这个问题有解决方法吗？
