### ISSUE TITLE
升级到最新flutter版本（1.10以上）打包后Crash，报NoClassDefFoundError，或java.lang.ExceptionInInitializerError

### ISSUE THREAD

**Issue by lawlietwind** [OpenFlutter/rammus#7]
[相关官方问题](https://help.aliyun.com/knowledge_detail/39998.html?spm=5176.11065259.1996646101.searchclickresult.19046b8e6FKDGQ&aly_as=_kpESz0V)并没有解决问题，解压后相关路径也存在。
不知道是否有人遇到这个问题，目前在flutter1.9版本不会出现问题，希望可以提供个思路解决。

**Comment by JarvanMo** [comment]
有可能是flutter 1.12默认开启了混淆。

**Comment by lawlietwind** [comment]
flutter更新有说明默认开启混淆吗，目前只有看到不会开启混淆，只能自己添加相关配置进行混淆和压缩代码。

**Comment by JarvanMo** [comment]
具体详细没考证，但是从收到的反馈来看应该是被混淆了。

**Comment by lawlietwind** [comment]
那我应该手动加上混淆然后忽略阿里云相关sdk吗，完整包名在官方文档没找到，不知道你是否了解？

**Comment by JarvanMo** [comment]
看看官方demo有没有混淆配置

**Comment by lawlietwind** [comment]
解决了，配置了混淆之后正常了，感谢提供思路:D。

**Comment by wasdty** [comment]
> 解决了，配置了混淆之后正常了，感谢提供思路:D。

请问是怎么配置混淆

**Comment by lawlietwind** [comment]
> > 解决了，配置了混淆之后正常了，感谢提供思路:D。
> 
> 请问是怎么配置混淆

https://help.aliyun.com/document_detail/51056.html?spm=a2c4g.11186623.6.556.15bd2055zeYsSL#3.5.%20Proguard%E9%85%8D%E7%BD%AE
