### ISSUE TITLE
支持小米华为离线推送吗

### ISSUE THREAD

**Issue by ihqrbb** [OpenFlutter/rammus#8]
支持小米华为离线推送吗

**Comment by JarvanMo** [comment]
不支持，需要自己集成

**Comment by ihqrbb** [comment]
大神 有时间集成一下吗

**Comment by ihqrbb** [comment]
> 不支持，需要自己集成

大神有时间集成一下吗

**Comment by JarvanMo** [comment]
抱歉时间精力有限------------------ 原始邮件 ------------------
发件人: "ihqrbb"<notifications@github.com>
发送时间: 2020年3月9日(星期一) 下午4:18
收件人: "OpenFlutter/rammus"<rammus@noreply.github.com>;
抄送: "JarvanMo"<468122151@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [OpenFlutter/rammus] 支持小米华为离线推送吗 (#8)


 
不支持，需要自己集成
  
大神有时间集成一下吗
 
&mdash;
